name: Build extension

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: nuget restore
      run: nuget restore -Verbosity quiet

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      id: build
      run: |
        msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    # Doing this in 2 steps instead of having two paths, because I want both .vsix files to be in the root of the zip file
    # and they won't be if they are uploaded in the same build
    
    - name: Store VS2019 VSIX Build
      uses: actions/upload-artifact@v2
      with:
        name: builds-for-vs2019-and-vs2022
        path: StopOnFirstBuildError2019/bin/Release/StopOnFirstBuildError2019.vsix

    - name: Store VS2022 VSIX Build
      uses: actions/upload-artifact@v2
      with:
        name: builds-for-vs2019-and-vs2022
        path: StopOnFirstBuildError2022/bin/Release/StopOnFirstBuildError2022.vsix
